# Generated by Django 4.2.3 on 2023-07-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_rename_amount_expense_sum_rename_amount_income_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='sum',
            field=models.IntegerField(null=True),
        ),
    ]
