# Generated by Django 4.2.3 on 2023-07-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_expense_sum_alter_income_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='sum',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='sum',
            new_name='amount',
        ),
    ]
